### PR TITLE
Remove paid AppStore apps from app_store_apps list

### PR DESCRIPTION
**Pull request by Reinboo**
When running the last step from this project there are multiple popups with the following message:
>This redownload is not available for this Apple ID either because it was bought by a different user or the item was refunded or cancelled.

This error shows up for two reasons:
1. Apple ID has been freshly created and macOS is asking for account information to be reviewed
2. You cannot purchase AppStore apps via `mas` since macOS 10.15 Catalina

---

1. This part is a bit glitchy because when you click "Review account information" it will asks you to login again via Apple ID in a loop. One possible workaround is to open `System Preferences`, go to `Media & Purchases` and log in from there to review your account info (you will have to add Address and phone number for payment; You don't have to enter credit/debit card) and then you should be able to download apps from AppStore. 

**Action Item**: Maybe we could include this step in Onboarding JIRA board before the Ansible Dotfiles task?

2. The ansible script is using `mas install <app_id>` to install apps from app store, but for apps that have to be purchased the command is `mas purchase <app_id>`.  Although, even the `purchase` command wouldn't fix it for macOS 10.15 Catalina and higher as the `purchase` command doesn't work (see [mas Known Issues](https://github.com/mas-cli/mas#%EF%B8%8F-known-issues)) and it would require that payment info is already supplied for the given apple ID. 

**Action Item**: This PR removes paid apps from the script since they don't seem essential for development and this issue will confuse newcomers. Also there doesn't seem to be a workaround to automate the process.  
**Please check this list change as I am new myself and maybe I just don't realise if these apps are essential or not!**

### CODE REVIEW

**Comment by aleksvidak** [comment]
@Reinboo do you think action item is still valid after merging the PR?

> Action Item: Maybe we could include this step in Onboarding JIRA board before the Ansible Dotfiles task?

**Comment by Reinboo** [comment]
> @Reinboo do you think action item is still valid after merging the PR?
> 
> > Action Item: Maybe we could include this step in Onboarding JIRA board before the Ansible Dotfiles task?

I would say yes, because that "Review account information" popup should appear on the first download for a fresh Apple ID, regardless of whether it's a free or paid app (This PR only removes paid apps from the list). But I don't know how to test that to confirm, at this point :/

**Review by aleksvidak — APPROVED** [review]
Thank you for being proactive to update the scripts. 🎊 
Can you please update https://3apjira.atlassian.net/browse/TEMP-21 template story for onboarding as well? 🙏🏻

**Comment by Reinboo** [comment]
The ticket is updated now :)

**Pull request merged**
